CREATE TABLE STV2024071542__DWH.CliTurnoverDtl
(
    DataInfo date NOT NULL,
    StoreCode varchar(21) NOT NULL,
    CliCode int NOT NULL,
    RgdCode int NOT NULL,
    ManCode int NOT NULL,
    Class37_Code varchar(18),
    Class55_Code varchar(2),
    TypeMan varchar(8),
    PrjCode int,
    TenderCode int,
    IsProject varchar(6),
    IsTender varchar(6),
    Nelikvid varchar(2),
    StoreCode1F varchar(20),
    ChannelSale varchar(20),
    SumSaled float,
    Cost float,
    SumRB float,
    QuantInv float,
    CostAcc float,
    QuantRgd float,
    TranspExpense float,
    CostOnShip float,
    CostRegional float,
    Cost81Orig float,
    NumKey int NOT NULL,
    YearInfo int NOT NULL,
    QuartInfo int NOT NULL,
    MonthInfo int NOT NULL,
    CostAccOnDtInfo float,
    TypeLogin varchar(20),
    WayToLuggInBasket varchar(20),
    CostForecastAccOnDtInfo float,
    ObjCode int,
    TypeLogin1 varchar(20),
    CostDSM float,
    IsCompl varchar(6),
    ShipmentSrc varchar(5),
    SalesChannel varchar(6),
    SalesSubChannel varchar(8),
    PlanDelivDate date,
    TypeExpDelivDate integer,
    ActDateOrdReady date,
    MethReceivingReq integer,
    TypeReq  integer,
    FirmPpl integer,
    CONSTRAINT fk_DescKontrag FOREIGN KEY (CliCode) REFERENCES STV2024071542__DWH.DescKontrag (CliCode),
    CONSTRAINT fk_RgdDivisDprt FOREIGN KEY (RgdCode) REFERENCES STV2024071542__DWH.RgdDivisDprt (RgdCode),
    CONSTRAINT fk_Class37 FOREIGN KEY (Class37_Code) REFERENCES STV2024071542__DWH.Class37 (Class37_Code)
)
PARTITION BY (CliTurnoverDtl.DataInfo) GROUP BY (date_trunc('year', CliTurnoverDtl.DataInfo)) ActivePartitionCount 4;